services:
  vh-dash:
    image: "${IMAGE_NAME}"
    cpus: '0.1'
    mem_limit: 50M
    ports:
      - 8080:80
    volumes:
      - /opt/vh/vh-dash/public/config/:/usr/share/nginx/html/config/
    restart: unless-stopped
networks:
  default:
    name: vh
    external: true
